apiVersion: openrhino.org/v1alpha2
kind: RhinoJob
metadata:
  name: rhinojob-sample-v1alpha2
spec:
  image: "openrhino/integration"
  ttl: 300
  parallelism: 2
  appExec: "/app/mpi-func"
  appArgs: ["1", "10", "1"]
