name: Continuous Delivery

on:
  push:
    branches:
      - main

  workflow_dispatch:

  workflow_run:
    workflows: ["Operator Automated Testing"]
    types:
      - completed

jobs:
  check_repository:
    runs-on: ubuntu-latest
    steps:
    - name: Check repository
      run: |
        if [[ "${{ github.repository }}" != "OpenRHINO/RHINO-Operator" ]]; then
          echo "The CD workflow runs only in the upstream OpenRHINO/RHINO-Operator repository.\n"
          echo "If you need to run the CD workflow in a fork repo, you may customize this workflow."
          exit 0
        fi

  deploy:
    runs-on: ubuntu-latest
    if: github.repository == 'OpenRHINO/RHINO-Operator'
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: openrhino
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      run: |
          make docker-build
          make docker-push